baseurl = "/docs/"
languageCode = "en-us"
title = "chat.io/docs"
disableHugoGeneratorInject = true
ignorefiles = ["/agent-api/api-reference/v0.2/examples/index.html", "/agent-api/api-reference/v0.3/examples/index.html", "/customer-api/api-reference/v0.2/examples/index.html", "/customer-api/api-reference/v0.3/examples/index.html"]

pygmentsCodeFences = true
pygmentsUseClassic=true
pygmentsUseClasses= true